mkdir Asset\ART
mkdir Asset\ART\Refs
mkdir Asset\ART\Wips
mkdir Asset\ART\Renders
mkdir Asset\MOD
mkdir Asset\MOD\Maya
mkdir Asset\MOD\ZB
mkdir Asset\MOD\MD
mkdir Asset\MOD\Others
mkdir Asset\MOD\Export
mkdir Asset\MOD\Export\msh
mkdir Asset\MOD\Export\tmp
mkdir Asset\MOD\Export\md
mkdir Asset\MOD\Export\ma
mkdir Asset\MOD\Export\for_bake\maps
mkdir Asset\SHD
mkdir Asset\SHD\Maya
mkdir Asset\SHD\SD
mkdir Asset\SHD\SP
mkdir Asset\SHD\Mari
mkdir Asset\SHD\Export\tmp
mkdir Asset\SHD\Export\shd
mkdir Asset\SHD\maps\F_ZB
mkdir Asset\Published
mkdir Asset\Files_From\client
mkdir Asset\Files_From\freelance